development:
  adapter: postgresql
  encoding: utf8
  database: eat_vegan_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: eat_vegan_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: eat_vegan_production
  pool: 5
  username: 
  password:
